modify first task

diff --git a/0x0C-web_server/0-transfer_file b/0x0C-web_server/0-transfer_file
--- a/0x0C-web_server/0-transfer_file
+++ b/0x0C-web_server/0-transfer_file
@@ -5,19 +5,29 @@
 #     - The IP of the server to transfer to
 #     - The username scp connects with
 #     - The path to the SSH private key that scp uses
-# - Display Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY if less than 3 parameters passed
-# - scp must transfer the file to the user home directory ~/
-# - Strict host key checking must be disabled when using scp
+# - Display Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY
 
-if [ $# -lt 3 ]
+if [ $# -lt 4 ]
 then
     echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
     exit 1
 fi
 
-if [ $# -eq 4 ]
+# assigning paramentals to variables
+
+path_to_file=$1
+ip=$2
+username=$3
+path_to_ssh_key=$4
+
+# disabbling strict host key checking
+scp -o "StrictHostKeyChecking=no" -i "$path_to_ssh_key" "$path_to_file" "$username@$ip:~/"
+
+# checking if the transfer was successful
+
+if [ $? -eq 0 ]
 then
-    scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3"@"$2":~/
+	echo "FILE WAS TRANSFERED SUCCESSFULLY"
 else
-    scp -o StrictHostKeyChecking=no "$1" "$3"@"$2":~/
+	echo "FILE TRANSFER FAILED"
 fi
